on:
  push:
    branches:
      - master
jobs:
  deploy_job:
    name: deploy
    runs-on: self-hosted
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: stop all bots
      run: 
        sudo sh /root/bots/stop.sh
    - name: build fatjar
      run: |
        sudo chmod +x gradlew
        sudo ./gradlew customFatJar
    - name: change jarfile
      run:
        sudo mv build/libs/discord_bot_ny-1.0.jar /root/bots/discord_bot_ny/discord_bot_ny-1.0.jar
    - name: start all bots
      run:
        sudo sh /root/bots/start.sh
